export { default as BorderBox1 } from './BorderBox1.vue'
export { default as BorderBox2 } from './BorderBox2.vue'
export { default as BorderBox3 } from './BorderBox3.vue'
export { default as BorderBox4 } from './BorderBox4.vue'
export { default as BorderBox5 } from './BorderBox5.vue'
export { default as BorderBox6 } from './BorderBox6.vue'
export { default as BorderBox7 } from './BorderBox7.vue'
